package:
  name: sherpa-samp
  version: "0.3.1"

build:
  number: "0"

requirements:
  build:
   - setuptools
   - python 2.7.*
   - numpy

  run:
   - setuptools
   - sherpa
   - astlib
   - scipy
   - numpy

about:
  home : https://github.com/ChandraCXC/sherpa-samp
  summary : samp interface for sherpa
  license: GPLv3
 
