package:
  name: sherpa-samp
  version: 3.0

build:
  number: 0

  preserve_egg_dir: yes

requirements:
  run:
   - setuptools
   - python 2.7.*
   - scipy
   - astlib
   - sherpa 4.8.*
   - numpy 1.8.*
   - sampy
   - sedstacker 0.1.0_iris

  build:
   - setuptools
   - python 2.7.*
   - numpy 1.8.*

about:
  home: https://github.com/ChandraCXC/sherpa-samp.git
  summary: SAMP interface to Sherpa.   
