package:
  name: sherpa-samp
  version: "2.1"

build:
  number: 1

  preserve_egg_dir: yes

requirements:
  run:
   - setuptools
   - python 2.7.*
   - scipy
   - astlib
   - sherpa
   - numpy 1.8.*
   - sampy

  build:
   - setuptools
   - python
   - numpy

about:
  home: https://github.com/ChandraCXC/sherpa-samp.git
  summary: SAMP interface to Sherpa.   
