package:
  name: sherpa-samp
  version: 3.0b1 

build:
  number: 0

  preserve_egg_dir: yes

requirements:
  run:
   - setuptools
   - python 2.7.*
   - scipy
   - astlib
   - sherpa
   - numpy
   - sampy
   - sedstacker 0.1.0_iris

  build:
   - setuptools
   - python
   - numpy

about:
  home: https://github.com/ChandraCXC/sherpa-samp.git
  summary: SAMP interface to Sherpa.   
